Fix new behavior introduced:
SquidGuard blacklist upload does not work. When I try to upload a new Shalla-Blacklist I get the following error:

Fatal error: Allowed memory size of 12582912 bytes exhausted (tried to allocate 9123462 bytes) in /usr/local/pkg/squidguard_configurator.inc on line 1647